[package]
name = "strands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10.14"
log = "0.4.19"
pretty_env_logger = "0.5.0"
tokio = { version = "1.30.0", features = ["full"] }
